### PR TITLE
add R/L key (switch multiple page)

### PR DESCRIPTION
**Pull request by SegFault42**
add R/L key for books with a lot of page

### CODE REVIEW

**Comment by joel16** [comment]
Sorry I've been busy with a bunch of stuff lately. I'll be travelling back to my university so I won't have time to test this until Sunday.

**Comment by joel16** [comment]
Seems to be a little slow, but is it meant to be that way? (Just making sure that this isn't just happening on my device) By slow I mean there is a 1-1.5 second delay, it's not instantaneous.

**Comment by SegFault42** [comment]
Yes it's slow. I can try to make it speeder.

**Comment by SegFault42** [comment]
it's faster now !

**Comment by joel16** [comment]
Works great, thanks!

**Pull request merged**
