### PR TITLE
Re-add book reader

### PR DESCRIPTION
**Pull request by uyjulian**
Requires the `switch-mupdf` package to be installed, which can be built using the PKGBUILD from my `switch-mupdf` branch on my `pacman-packages` repository.

### CODE REVIEW

**Comment by joel16** [comment]
This was removed for a reason. Unless you plan on fixing the issues that it had there are no plans on bringing it back.

**Comment by uyjulian** [comment]
What issues? I got mupdf working.

**Comment by joel16** [comment]
It was already "working" before. Have a look at some of the closed issues relating to the PDF reader.

**Comment by joel16** [comment]
Feel free to let me know if you wish to fix any of those issues, then i'll happily re-open this.

**Pull request closed without merging**
