### PR TITLE
add Chinese language

### PR DESCRIPTION
**Pull request by tiansongyu**

### CODE REVIEW

**Comment by joel16** [comment]
Thank you!

**Comment by tiansongyu** [comment]
Done! 
I have a question. why do you use in this way [https://github.com/joel16/NX-Shell/blob/61fbae92a865ba292ce1eddc7745d76c07bbd777/source/main.cpp#L138-L142](https://github.com/joel16/NX-Shell/blob/61fbae92a865ba292ce1eddc7745d76c07bbd777/source/main.cpp#L138-L142)

Most of language characters are provided by libnx [here](https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/pl.h#L18-L24)
and you can use it in this [in this way](https://github.com/switchbrew/switch-examples/blob/fc98393d50e7896fcc8d59295516c2d1640f043f/graphics/shared_font/source/main.c#L152-L165)

**Comment by tiansongyu** [comment]
[This](https://github.com/averne/Turnips/blob/81c1592672176d22be9f87fd9619c1dd1da0a19a/src/imgui_nx/imgui_nx.cpp#L124-L142) is the detailed usage

**Comment by joel16** [comment]
Hey, 
Yes I am aware of using the switch's official system font, however using that causes some alignment issues with the file icons. Once I sort that out I will move towards using the system font. This is just temporary for now. I don't want to release it this way since the current font bundled in takes up a lot of space also slows down boot time by like 4 seconds.

**Comment by tiansongyu** [comment]
I know the app is slower to start up because of it needs to build the font atlas with other characters.
Looking forward to your  new update ! cheer~

**Pull request merged**
